// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(FutureVestContext))]
    partial class FutureVestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Persistence.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Persistence.Entities.EconomicIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("MacroeconomicIndicatorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("MacroeconomicIndicatorId");

                    b.ToTable("EconomicIndicator");
                });

            modelBuilder.Entity("Persistence.Entities.EstimatedRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EstimatedRate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxRate = 15m,
                            MinRate = 2m
                        });
                });

            modelBuilder.Entity("Persistence.Entities.MacroeconomicIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HigherIsBetter")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WeightFactor")
                        .HasMaxLength(1)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MacroeconomicIndicator");
                });

            modelBuilder.Entity("Persistence.Entities.SimulationMacroIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RealMacroIndicatorId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightFactor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RealMacroIndicatorId")
                        .IsUnique();

                    b.ToTable("SimulationMacroIndicator");
                });

            modelBuilder.Entity("Persistence.Entities.EconomicIndicator", b =>
                {
                    b.HasOne("Persistence.Entities.Country", "Country")
                        .WithMany("EconomicIndicators")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Entities.MacroeconomicIndicator", "MacroeconomicIndicator")
                        .WithMany("EconomicIndicators")
                        .HasForeignKey("MacroeconomicIndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("MacroeconomicIndicator");
                });

            modelBuilder.Entity("Persistence.Entities.SimulationMacroIndicator", b =>
                {
                    b.HasOne("Persistence.Entities.MacroeconomicIndicator", "RealMacroIndicator")
                        .WithOne("SimulationMacroIndicator")
                        .HasForeignKey("Persistence.Entities.SimulationMacroIndicator", "RealMacroIndicatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("RealMacroIndicator");
                });

            modelBuilder.Entity("Persistence.Entities.Country", b =>
                {
                    b.Navigation("EconomicIndicators");
                });

            modelBuilder.Entity("Persistence.Entities.MacroeconomicIndicator", b =>
                {
                    b.Navigation("EconomicIndicators");

                    b.Navigation("SimulationMacroIndicator");
                });
#pragma warning restore 612, 618
        }
    }
}
